FROM node:14.4.0 AS compile-image

WORKDIR /root

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN ["chmod", "+x", "/docker-entrypoint.sh"]
ENTRYPOINT [ "/docker-entrypoint.sh" ]

RUN npm install -g typescript
RUN npm install -g @angular/cli 
RUN npm install -g gulp-cli