version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    volumes:
      - ./config/nginx-maxsize.conf:/etc/nginx/conf.d/nginx-maxsize.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: none
    ports:
      - "80:80"
      - "443:443"

  nginx:
    image: nginx:1.18.0-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - VIRTUAL_HOST=igualdad.local

  back:
    build:
      context: .
      dockerfile: Dockerfile-back
    restart: unless-stopped
    environment:
      - CONFIGFILE=/app/cfg/config.json
      - CONPOSE_CONVERT_WINDOWS_PATHS=true
    volumes:
      - ./../../igualdad-back:/app/back:cached
      - ./config/config.json:/app/cfg/config.json:cached
    working_dir: /app/back
    ports: 
      - "3890:389"
    depends_on: 
      - db
      - ldap
    command: bra run

  front:
    build:
        context: .
        dockerfile: Dockerfile-front
    restart: unless-stopped
    volumes:
      - ./../../igualdad-front:/app/front:cached
    working_dir: /app/front
    command: npm run start

  db:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=DifficultPassword

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    restart: unless-stopped
    volumes:
      - ./config/phpmyadmin-config-user.php:/etc/phpmyadmin/config.user.inc.php:cached
    environment:
      - PMA_HOST=mysql
      - PMA_PMADB=pma
      - PMA_USER=root
      - PMA_PASSWORD=DifficultPassword
      - VIRTUAL_HOST=igualdad-db.local
    logging:
      driver: none

  ldap:
    image: osixia/openldap:1.4.0
    restart: unless-stopped
    ports: 
      - "3389:389"